# Generated by Django 3.2.6 on 2021-11-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('desig', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=7)),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.TextField()),
                ('type', models.TextField()),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('step', models.IntegerField()),
            ],
        ),
    ]
